# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Blockchain App CI

on:
  push:
    # Only trigger if files in this path changed
    paths:
      - 'blockchain-app/client/**'
      - '.github/workflows/blockchain**'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  pull_request:
    # Only trigger if files in this path changed
    paths:
      - 'blockchain-app/client/**'
      - '.github/workflows/blockchain.app.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./blockchain-app/client/

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        working-directory: blockchain-app/client
    - name: Install dependencies 📦
      #Using npm ci is generally faster than running npm install
      run: |
        npm ci
    - name: Build the app for prod 🏗
      run: |
        npm run build
    - name: Start the app 📤
      #Vite has a different command for deploy than vanilla react
      run: |
        npm run preview &
        npx wait-on --timeout 60000
    - name: Run visual tests 👁
      run: |
        npm run cy:visual
